### PR TITLE
Build with BinaryProvider

### PR DESCRIPTION
**Pull request by IanButterworth**
- New auto build with binaryprovider so that ANTSPATH setting isn't required. Currently supports:
 ```
MacOS(:x86_64)
Linux(:x86_64, libc=:glibc)
Windows(:x86_64)
```
- Added `suppressout::Bool=false` to `register()` for a heavy-handed way to suppress output

### CODE REVIEW

**Comment by timholy** [comment]
Sorry to be slow to notice this, I've been swamped with implementing the new debugger (official announcement going out today).

Seems like a great idea. Travis says it's not working yet, but I'll be happy to merge when it does. I'm not familiar enough with BinaryProvider to offer useful feedback.

For the moment REQUIRE is still needed if one wants to register the package. (Not sure if I do, but not a bad idea if folks find it useful.)

**Comment by IanButterworth** [comment]
@timholy Great! Looking forward to the announcement.

I've corrected the test failures (hash and GIT-LFS -related errors on the binaries and linking to $antsMotionCorr properly) but it looks like there's a test value mismatch error that it would be good for you to review given I don't immediately understand the implication:
```
Anisotropic spacing: Test Failed at /home/travis/build/timholy/ANTsRegistration.jl/test/runtests.jl:148
  Expression: 1.01 * mean(mappedarray(diff2_0, fixed0, imgw0)) >= mean(mappedarray(diff2_0, fixed, imgw))
   Evaluated: 0.01087339681093852 >= 0.012277198189111533
```

**Comment by timholy** [comment]
Not necessary to wait:
https://julialang.org/blog/2019/03/debuggers
https://discourse.julialang.org/t/debugging-julia/22147/22

I'll look at that error. It's been a while since I used this.

**Comment by IanButterworth** [comment]
Much appreciated. I haven't explored your registration packages yet, but perhaps working on ANTS is wasted time if you've built out the key registration functionality already..

But if it's a simple fix..

**Comment by timholy** [comment]
I've looked at the error, and it's not one to worry about. Maybe a small change in interpolation scheme or something. I'll merge this and then submit a patch that makes the tests pass. (It will also have more comments in that section so you can understand what it's all about...)

**Comment by timholy** [comment]
> perhaps working on ANTS is wasted time if you've built out the key registration functionality already..

I don't think so. Registration is *hard* and ANTs is very good. That said, it's far from perfect. Our RegisterQD package may yield higher quality on rigid registration? We've never done a head-to-head comparison, that's just a subjective guess.

When it comes to deformable registration, I would bet that ANTs is better than us. Again just a guess.

**Comment by Tokazama** [comment]
It may be worth mentioning that a lot of ANTs is built from a handful of key compiled code that's put together in a variety of bash scripts. I imagine Julia could really help with compiling pipelines that use these scripts on images with the same parameters.

It seems like a lot of the purely ITK based stuff and stats related functionality wouldn't be that hard to implement in Julia, if it isn't already present. But without implementation of their symmetric diffeomorphic registration technique I think it would be hard to really use Julia instead.

**Pull request merged**
